"""Codegen — emit an OpenAPI 3 spec from the catalog.

Every endpoint becomes a path/operation with an inferred response schema.
Rosetta's decoded meanings ride along as an ``x-glyph-dictionary``
vendor extension per operation, so the codes are documented where a
consumer will read them. Codegen off a single target over-fits
(RESEARCH.md §8) — treat the output as a starting draft.
"""
from __future__ import annotations

import json
from collections import defaultdict
from typing import Any, Dict, List

from glyph.catalog import Catalog
from glyph.schema.infer import build_schema


def _response_docs(catalog: Catalog, endpoint_id: int) -> List[Any]:
    docs = []
    for f in catalog.flows_for_endpoint(endpoint_id):
        if not f.resp_body:
            continue
        looks_json = (f.resp_mime or "").endswith("json") or \
            f.resp_body.lstrip()[:1] in "{["
        if not looks_json:
            continue
        try:
            docs.append(json.loads(f.resp_body))
        except (ValueError, TypeError):
            continue
    return docs


def to_openapi(catalog: Catalog, title: str = "Glyph-decoded API",
               version: str = "0.1.0") -> Dict[str, Any]:
    """Build an OpenAPI 3.0.3 document from the catalog."""
    endpoints = catalog.endpoints()
    hosts = sorted({e.host for e in endpoints if e.host})

    dict_by_ep: Dict[Any, List] = defaultdict(list)
    for entry in catalog.dictionary():
        dict_by_ep[entry.endpoint_id].append(entry)

    paths: Dict[str, Dict[str, Any]] = defaultdict(dict)
    for ep in endpoints:
        schema = build_schema(_response_docs(catalog, ep.id)) if ep.id else None
        operation: Dict[str, Any] = {
            "summary": f"{ep.method} {ep.path_template}",
            "responses": {
                "200": {
                    "description": "Observed response",
                    "content": {"application/json": {
                        "schema": schema or {"type": "object"}}},
                }
            },
        }
        if ep.reachability and ep.reachability != "direct":
            operation["x-glyph-reachability"] = ep.reachability

        decoded = dict_by_ep.get(ep.id) or []
        if decoded:
            by_path: Dict[str, Dict[str, Any]] = defaultdict(dict)
            for d in decoded:
                by_path[d.json_path][str(d.code)] = {
                    "meaning": d.meaning,
                    "confidence": d.confidence,
                    "needs_review": d.needs_review,
                }
            operation["x-glyph-dictionary"] = by_path

        paths[ep.path_template][ep.method.lower()] = operation

    return {
        "openapi": "3.0.3",
        "info": {"title": title, "version": version,
                 "description": "Generated by Glyph from observed traffic."},
        "servers": [{"url": f"https://{h}"} for h in hosts] or
                   [{"url": "/"}],
        "paths": dict(paths),
    }


def to_openapi_json(catalog: Catalog, **kwargs: Any) -> str:
    return json.dumps(to_openapi(catalog, **kwargs), indent=2, ensure_ascii=False)
